# HorizontalPodAutoscaler for production (optional)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: holostrap-prod-hpa
  namespace: holochain
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: holostrap-prod
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80